# Generated by Django 6.0 on 2026-02-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apropos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='À propos de moi', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='apropos/')),
                ('description', models.TextField(help_text='Racontez votre parcours culinaire ici')),
                ('citation', models.CharField(blank=True, help_text='Une petite phrase qui vous inspire', max_length=255)),
            ],
            options={
                'verbose_name': 'À Propos',
                'verbose_name_plural': 'À Propos',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('salade', 'Salade'), ('plat_burkinabe', 'Plat burkinabé'), ('plat_international', 'Plat international'), ('dessert', 'Dessert'), ('boisson', 'Boisson | Cocktail'), ('petit_dejeuner', 'Petit-déjeuner')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recettes/')),
                ('ingredients', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('jour_menu', models.CharField(choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi'), ('SAMEDI', 'Samedi'), ('DIMANCHE', 'Dimanche'), ('AUCUN', 'Pas au menu')], default='AUCUN', max_length=20, verbose_name='Jour de vente')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('prix', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Prix (FCFA)')),
                ('temps_cuisson', models.IntegerField(default=0, verbose_name='Temps de cuisson (minutes)')),
            ],
        ),
        migrations.CreateModel(
            name='Utile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre ou Saison')),
                ('categorie', models.CharField(choices=[('calendrier', 'Calendrier des fruits & légumes de saison'), ('materiel', 'Mon matériel de cuisine'), ('sante', 'Rééquilibrage alimentaire')], max_length=50)),
                ('liste_fruits', models.TextField(blank=True, help_text='Uniquement pour le calendrier')),
                ('liste_legumes', models.TextField(blank=True, help_text='Uniquement pour le calendrier')),
                ('description_generale', models.TextField(blank=True, help_text='Pour le matériel ou la santé')),
                ('image', models.ImageField(blank=True, null=True, upload_to='utiles/')),
            ],
        ),
    ]
