# Generated by Django 6.0.1 on 2026-02-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('salade', 'Salade'), ('plat_burkinabe', 'Plat burkinabé'), ('plat_international', 'Plat international'), ('dessert', 'Dessert'), ('boisson', 'Boisson | Cocktail'), ('petit_dejeuner', 'Petit-déjeuner')], max_length=50)),
                ('image', models.ImageField(upload_to='recettes/')),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
