# Generated by Django 6.0 on 2026-02-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apropos',
            name='image_statique',
            field=models.CharField(blank=True, help_text='Exemple: cuisine/regina.jpg', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recette',
            name='image_statique',
            field=models.CharField(blank=True, help_text='Exemple: cuisine/riz_gras.jpg', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='utile',
            name='image_statique',
            field=models.CharField(blank=True, help_text='Exemple: cuisine/materiel.jpg', max_length=255, null=True),
        ),
    ]
