# Generated by Django 6.0 on 2026-02-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recette',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='recette',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='recette',
            name='image',
        ),
        migrations.RemoveField(
            model_name='recette',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recette',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='recette',
            name='titre',
        ),
        migrations.AddField(
            model_name='recette',
            name='jour_menu',
            field=models.CharField(choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi'), ('SAMEDI', 'Samedi'), ('DIMANCHE', 'Dimanche'), ('AUCUN', 'Pas au menu')], default='AUCUN', max_length=20, verbose_name='Jour de vente'),
        ),
    ]
