# Generated by Django 6.0 on 2026-02-04 11:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0002_remove_recette_categorie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='categorie',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recette',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recette',
            name='image',
            field=models.ImageField(default='', upload_to='recettes/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recette',
            name='jour_menu',
            field=models.CharField(choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi'), ('SAMEDI', 'Samedi'), ('DIMANCHE', 'Dimanche'), ('AUCUN', 'Pas au menu')], default='AUCUN', max_length=20),
        ),
    ]
