# Generated by Django 6.0 on 2026-02-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0004_recette_ingredients_recette_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='categorie',
            field=models.CharField(choices=[('salade', 'Salade'), ('plat_burkinabe', 'Plat burkinabé'), ('plat_international', 'Plat international'), ('dessert', 'Dessert'), ('boisson', 'Boisson | Cocktail'), ('petit_dejeuner', 'Petit-déjeuner')], max_length=50),
        ),
        migrations.AlterField(
            model_name='recette',
            name='jour_menu',
            field=models.CharField(choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi'), ('SAMEDI', 'Samedi'), ('DIMANCHE', 'Dimanche'), ('AUCUN', 'Pas au menu')], default='AUCUN', max_length=20, verbose_name='Jour de vente'),
        ),
    ]
