# Generated by Django 6.0 on 2026-02-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0005_alter_recette_categorie_alter_recette_jour_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='prix',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Prix (FCFA)'),
        ),
        migrations.AddField(
            model_name='recette',
            name='temps_cuisson',
            field=models.IntegerField(default=0, verbose_name='Temps de cuisson (minutes)'),
        ),
    ]
