# Generated by Django 6.0 on 2026-02-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0006_recette_prix_recette_temps_cuisson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('legumes_saison', 'Calendrier des fruits et légumes de saison'), ('materiel', 'Mon matériel de cuisine'), ('sante', 'Rééquilibrage alimentaire et Santé')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='utiles/')),
                ('contenu', models.TextField(help_text="Décrivez les bienfaits ou l'utilisation de l'outil")),
                ('saison', models.CharField(blank=True, help_text='Ex: Printemps (pour les légumes)', max_length=50)),
            ],
        ),
    ]
