# Generated by Django 6.0 on 2026-02-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0008_alter_utile_saison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utile',
            name='saison',
            field=models.CharField(blank=True, choices=[('printemps', 'Printemps'), ('été', 'Été'), ('automne', 'Automne'), ('hiver', 'Hiver'), ('toutes', 'Toutes les saisons')], default='toutes', max_length=20, verbose_name='Saison concernée'),
        ),
    ]
