# Generated by Django 6.0 on 2026-02-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0009_alter_utile_saison'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendrierSaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saison', models.CharField(choices=[('HIVER', 'Hiver'), ('PRINTEMPS', 'Printemps'), ('ETE', 'Été'), ('AUTOMNE', 'Automne')], max_length=20, unique=True)),
                ('liste_fruits', models.TextField(help_text='Liste des fruits (ex: Banane - Citron - Fraise)')),
                ('liste_legumes', models.TextField(help_text='Liste des légumes (ex: Carotte - Épinard)')),
            ],
        ),
        migrations.RemoveField(
            model_name='utile',
            name='saison',
        ),
        migrations.AlterField(
            model_name='utile',
            name='categorie',
            field=models.CharField(choices=[('materiel', 'Mon matériel de cuisine'), ('sante', 'Rééquilibrage alimentaire et Santé')], max_length=50),
        ),
        migrations.AlterField(
            model_name='utile',
            name='contenu',
            field=models.TextField(),
        ),
    ]
