# Generated by Django 6.0 on 2026-02-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0010_calendriersaison_remove_utile_saison_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalendrierSaison',
        ),
        migrations.RemoveField(
            model_name='utile',
            name='contenu',
        ),
        migrations.AddField(
            model_name='utile',
            name='description_generale',
            field=models.TextField(blank=True, help_text='Pour le matériel ou la santé'),
        ),
        migrations.AddField(
            model_name='utile',
            name='liste_fruits',
            field=models.TextField(blank=True, help_text='Uniquement pour le calendrier'),
        ),
        migrations.AddField(
            model_name='utile',
            name='liste_legumes',
            field=models.TextField(blank=True, help_text='Uniquement pour le calendrier'),
        ),
        migrations.AlterField(
            model_name='utile',
            name='categorie',
            field=models.CharField(choices=[('calendrier', 'Calendrier des fruits & légumes de saison'), ('materiel', 'Mon matériel de cuisine'), ('sante', 'Rééquilibrage alimentaire')], max_length=50),
        ),
        migrations.AlterField(
            model_name='utile',
            name='titre',
            field=models.CharField(max_length=200, verbose_name='Titre ou Saison'),
        ),
    ]
