# Generated by Django 6.0 on 2026-02-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0011_delete_calendriersaison_remove_utile_contenu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apropos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='À propos de moi', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='apropos/')),
                ('description', models.TextField(help_text='Racontez votre parcours culinaire ici')),
                ('citation', models.CharField(blank=True, help_text='Une petite phrase qui vous inspire', max_length=255)),
            ],
            options={
                'verbose_name': 'À Propos',
                'verbose_name_plural': 'À Propos',
            },
        ),
    ]
